server:
  port: 8080
  #ssl:
    # You must add the certificate to the Java Key Store with cacerts
    #key-store: classpath:xxx.jks
    #key-store-password: xxx

spring:
  data:
    mongodb:
      uri: mongodb://localhost/movies

logging:
  level:
    org.springframework: INFO
